/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asseinfo_poker;

import java.text.ParseException;
import java.util.Arrays;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Carlos
 */
public class Cartas extends javax.swing.JFrame {

    int[] resultado = new int[2];

    /**
     * Creates new form Cartas
     */
    public Cartas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Player 1");

        jLabel2.setText("Player 2");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        jButton1.setText("Verificar Ganhador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String vMsgP1 = null;
        String vMsgP2 = null;
        int P1Num[] = new int[5];
        int P2Num[] = new int[5];
        char Separa[] = new char[3];

        String P1CartaNumero[] = new String[5];

        if (jTextField1.getText().isEmpty()
                || jTextField2.getText().isEmpty()
                || jTextField3.getText().isEmpty()
                || jTextField4.getText().isEmpty()
                || jTextField5.getText().isEmpty()
                || jTextField6.getText().isEmpty()
                || jTextField7.getText().isEmpty()
                || jTextField8.getText().isEmpty()
                || jTextField9.getText().isEmpty()
                || jTextField10.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completar todos os campos");

        } else {

            String arrp1[] = new String[5];
            String arrp2[] = new String[5];

            arrp1[0] = jTextField1.getText();
            arrp1[1] = jTextField4.getText();
            arrp1[2] = jTextField6.getText();
            arrp1[3] = jTextField8.getText();
            arrp1[4] = jTextField10.getText();

            arrp2[0] = jTextField2.getText();
            arrp2[1] = jTextField3.getText();
            arrp2[2] = jTextField5.getText();
            arrp2[3] = jTextField7.getText();
            arrp2[4] = jTextField9.getText();

            verifica_cartas vc = new verifica_cartas();
            vc.verificaP1(arrp1);
            vMsgP1 = vc.vMsgP1;
            vc.verificaP2(arrp2);
            vMsgP2 = vc.vMsgP2;
            if (vMsgP1.equals("OK") & vMsgP2.equals("OK")) {
                testa_ganhador testa = new testa_ganhador();
                testa.Test(arrp1, arrp2);
                if (testa.vResultado[0] > testa.vResultado[1]) {
                    JOptionPane.showMessageDialog(null, "Player 1 Vencedor");
                } else if (testa.vResultado[1] > testa.vResultado[0]) {
                    JOptionPane.showMessageDialog(null, "Player 2 Vencedor");
                } else {
                    //empate, verifica carta mais alta

                    for (int i = 0; i < 5; i++) {
                        Separa = arrp1[i].toCharArray();

                        int c = Separa.length;
                        if (c == 2) {
                            P1CartaNumero[i] = Character.toString(Separa[0]);
                            switch (P1CartaNumero[i]) {
                                case "A":
                                    P1CartaNumero[i] = "14";
                                    break;
                                case "K":
                                    P1CartaNumero[i] = "13";
                                    break;
                                case "Q":
                                    P1CartaNumero[i] = "12";
                                    break;
                                case "J":
                                    P1CartaNumero[i] = "11";
                                    break;
                            }
                        } else {
                            P1CartaNumero[i] = "10";
                        }
                        P1Num[i] = Integer.parseInt(P1CartaNumero[i]);
                    }
                    Arrays.sort(P1Num);
                    for (int i = 0; i < 5; i++) {
                        Separa = arrp2[i].toCharArray();
                        int c = Separa.length;
                        if (c == 2) {
                            P1CartaNumero[i] = Character.toString(Separa[0]);
                            switch (P1CartaNumero[i]) {
                                case "A":
                                    P1CartaNumero[i] = "14";
                                    break;
                                case "K":
                                    P1CartaNumero[i] = "13";
                                    break;
                                case "Q":
                                    P1CartaNumero[i] = "12";
                                    break;
                                case "J":
                                    P1CartaNumero[i] = "11";
                                    break;
                            }
                        } else {
                            P1CartaNumero[i] = "10";
                        }
                        P2Num[i] = Integer.parseInt(P1CartaNumero[i]);
                    }
                    Arrays.sort(P2Num);
                    if (P1Num[4] > P2Num[4]) {
                        JOptionPane.showMessageDialog(null, "Player 1 Vencedor");
                    } else if (P1Num[4] < P2Num[4]) {
                        JOptionPane.showMessageDialog(null, "Player 2 Vencedor");
                    } else {
                        JOptionPane.showMessageDialog(null, "Empate");
                    }
                }
            } else {
                if (vMsgP1.equals("OK")) {
                    JOptionPane.showMessageDialog(null, vMsgP2);
                } else {
                    JOptionPane.showMessageDialog(null, vMsgP1);
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField1.setText(this.jTextField1.getText().toUpperCase());
        int c = this.jTextField1.getText().length();
        if (c > 2) {
            Separa = this.jTextField1.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField1.setText(this.jTextField1.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField1.setText(this.jTextField1.getText().substring(0, c - 1));
            }
        }

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField4.setText(this.jTextField4.getText().toUpperCase());
        int c = this.jTextField4.getText().length();
        if (c > 2) {
            Separa = this.jTextField4.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField4.setText(this.jTextField4.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField4.setText(this.jTextField4.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField6.setText(this.jTextField6.getText().toUpperCase());
        int c = this.jTextField6.getText().length();
        if (c > 2) {
            Separa = this.jTextField6.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField6.setText(this.jTextField6.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField6.setText(this.jTextField6.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField8.setText(this.jTextField8.getText().toUpperCase());
        int c = this.jTextField8.getText().length();
        if (c > 2) {
            Separa = this.jTextField8.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField8.setText(this.jTextField8.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField8.setText(this.jTextField8.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField10.setText(this.jTextField10.getText().toUpperCase());
        int c = this.jTextField10.getText().length();
        if (c > 2) {
            Separa = this.jTextField10.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField10.setText(this.jTextField10.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField10.setText(this.jTextField10.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField2.setText(this.jTextField2.getText().toUpperCase());
        int c = this.jTextField2.getText().length();
        if (c > 2) {
            Separa = this.jTextField2.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField2.setText(this.jTextField2.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField2.setText(this.jTextField2.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField3.setText(this.jTextField3.getText().toUpperCase());
        int c = this.jTextField3.getText().length();
        if (c > 2) {
            Separa = this.jTextField3.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField3.setText(this.jTextField3.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField3.setText(this.jTextField3.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String P1CartaNumero = null;
        String c1 = null;
        String c2 = null;
        this.jTextField5.setText(this.jTextField5.getText().toUpperCase());
        int c = this.jTextField5.getText().length();
        if (c > 2) {
            Separa = this.jTextField5.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField5.setText(this.jTextField5.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField5.setText(this.jTextField5.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String c1 = null;
        String c2 = null;
        this.jTextField7.setText(this.jTextField7.getText().toUpperCase());
        int c = this.jTextField7.getText().length();
        if (c > 2) {
            Separa = this.jTextField7.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField7.setText(this.jTextField7.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField7.setText(this.jTextField7.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
        char Separa[] = new char[3];
        String c1 = null;
        String c2 = null;
        this.jTextField9.setText(this.jTextField9.getText().toUpperCase());
        int c = this.jTextField9.getText().length();
        if (c > 2) {
            Separa = this.jTextField9.getText().toCharArray();
            c1 = Character.toString(Separa[0]);
            c2 = Character.toString(Separa[1]);
            if (c1.equals("1") & c2.equals("0")) {
              if (c > 3) {
                this.jTextField9.setText(this.jTextField9.getText().substring(0, c - 1));
              }  
            } else {
               this.jTextField9.setText(this.jTextField9.getText().substring(0, c - 1));
            }
        }
    }//GEN-LAST:event_jTextField9KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
